### Send POST request with json body
https://www.dictionaryapi.com/api/v3/references/spanish/json/test?key={{translation-api-key}}

### Send POST request with json body
POST localhost:8765/addNotes
Content-Type: application/json

